-- CRM production migration script for PostgreSQL.
-- Generated for the current application migration set.
-- Safe to rerun: every migration is guarded by "__EFMigrationsHistory"."MigrationId".

BEGIN;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- -------------------------------------------------------------------------
-- 20260218175246_IdentityInitial
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260218175246_IdentityInitial') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Description" text NOT NULL,
        "IsSystemRole" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "Name" character varying(256) NULL,
        "NormalizedName" character varying(256) NULL,
        "ConcurrencyStamp" text NULL,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "AspNetUsers" (
        "Id" uuid NOT NULL,
        "FullName" text NOT NULL,
        "Address" text NOT NULL,
        "DepartmentId" uuid NULL,
        "LastLoginAt" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        "ForcePasswordChange" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "UpdatedBy" uuid NULL,
        "UserName" character varying(256) NULL,
        "NormalizedUserName" character varying(256) NULL,
        "Email" character varying(256) NULL,
        "NormalizedEmail" character varying(256) NULL,
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text NULL,
        "SecurityStamp" text NULL,
        "ConcurrencyStamp" text NULL,
        "PhoneNumber" text NULL,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone NULL,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text NULL,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
    );

    CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId")
    );

    CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text NULL,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetRoleClaims_AspNetRoles_RoleId') THEN
        ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUserClaims_AspNetUsers_UserId') THEN
        ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUserLogins_AspNetUsers_UserId') THEN
        ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUserRoles_AspNetRoles_RoleId') THEN
        ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUserRoles_AspNetUsers_UserId') THEN
        ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUserTokens_AspNetUsers_UserId') THEN
        ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260218175246_IdentityInitial', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260418120000_AddManagerIdToUsers
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418120000_AddManagerIdToUsers') THEN
        RETURN;
    END IF;

    ALTER TABLE "AspNetUsers" ADD COLUMN IF NOT EXISTS "ManagerId" uuid NULL;
    CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_ManagerId" ON "AspNetUsers" ("ManagerId");

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_AspNetUsers_AspNetUsers_ManagerId') THEN
        ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_AspNetUsers_ManagerId"
        FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL;
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418120000_AddManagerIdToUsers', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260418130000_AddRoleAuditAndCode
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418130000_AddRoleAuditAndCode') THEN
        RETURN;
    END IF;

    ALTER TABLE "AspNetRoles"
        ADD COLUMN IF NOT EXISTS "Code" text NULL,
        ADD COLUMN IF NOT EXISTS "CreatedBy" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
        ADD COLUMN IF NOT EXISTS "CreatedOn" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ADD COLUMN IF NOT EXISTS "UpdatedBy" uuid NULL,
        ADD COLUMN IF NOT EXISTS "UpdatedOn" timestamp with time zone NULL;

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_AspNetRoles_Code" ON "AspNetRoles" ("Code") WHERE "Code" IS NOT NULL;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418130000_AddRoleAuditAndCode', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260503193000_LeadsInitial
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260503193000_LeadsInitial') THEN
        RETURN;
    END IF;

    CREATE SCHEMA IF NOT EXISTS "leads";

    CREATE TABLE IF NOT EXISTS "leads"."Countries" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."Industries" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Industries" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."LeadCategories" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_LeadCategories" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."Partners" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Partners" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."LeadSources" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "RequiresPartner" boolean NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_LeadSources" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."Products" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CategoryName" text NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."Leads" (
        "Id" uuid NOT NULL,
        "LeadNumber" character varying(30) NOT NULL,
        "SourceId" uuid NOT NULL,
        "CategoryId" uuid NOT NULL,
        "PartnerId" uuid NULL,
        "CampaignName" text NULL,
        "CompanyName" character varying(250) NOT NULL,
        "Website" text NULL,
        "ContactPersonName" character varying(200) NOT NULL,
        "JobTitle" text NULL,
        "Email" character varying(250) NULL,
        "Phone" character varying(50) NULL,
        "AlternatePhone" text NULL,
        "CountryId" uuid NOT NULL,
        "Address" text NULL,
        "IndustryId" uuid NULL,
        "Notes" text NULL,
        "LeadScore" integer NULL,
        "Status" integer NOT NULL,
        "AssignedToUserId" uuid NULL,
        "AssignedAt" timestamp with time zone NULL,
        "QualificationDate" timestamp with time zone NULL,
        "DisqualificationReason" text NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Leads" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."LeadProductInterests" (
        "Id" uuid NOT NULL,
        "LeadId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_LeadProductInterests" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."LeadTimelineEntries" (
        "Id" uuid NOT NULL,
        "LeadId" uuid NOT NULL,
        "EventType" text NOT NULL,
        "Description" text NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_LeadTimelineEntries" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Countries_CountryId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "leads"."Countries" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Industries_IndustryId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_Industries_IndustryId" FOREIGN KEY ("IndustryId") REFERENCES "leads"."Industries" ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_LeadCategories_CategoryId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_LeadCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "leads"."LeadCategories" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_LeadSources_SourceId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_LeadSources_SourceId" FOREIGN KEY ("SourceId") REFERENCES "leads"."LeadSources" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Partners_PartnerId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_Partners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES "leads"."Partners" ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LeadProductInterests_Leads_LeadId') THEN
        ALTER TABLE "leads"."LeadProductInterests" ADD CONSTRAINT "FK_LeadProductInterests_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "leads"."Leads" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LeadProductInterests_Products_ProductId') THEN
        ALTER TABLE "leads"."LeadProductInterests" ADD CONSTRAINT "FK_LeadProductInterests_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "leads"."Products" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LeadTimelineEntries_Leads_LeadId') THEN
        ALTER TABLE "leads"."LeadTimelineEntries" ADD CONSTRAINT "FK_LeadTimelineEntries_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "leads"."Leads" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Countries_Code" ON "leads"."Countries" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Industries_Code" ON "leads"."Industries" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_LeadCategories_Code" ON "leads"."LeadCategories" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_LeadSources_Code" ON "leads"."LeadSources" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Partners_Code" ON "leads"."Partners" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Code" ON "leads"."Products" ("Code");
    CREATE INDEX IF NOT EXISTS "IX_Leads_CategoryId" ON "leads"."Leads" ("CategoryId");
    CREATE INDEX IF NOT EXISTS "IX_Leads_CountryId" ON "leads"."Leads" ("CountryId");
    CREATE INDEX IF NOT EXISTS "IX_Leads_IndustryId" ON "leads"."Leads" ("IndustryId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Leads_LeadNumber" ON "leads"."Leads" ("LeadNumber");
    CREATE INDEX IF NOT EXISTS "IX_Leads_PartnerId" ON "leads"."Leads" ("PartnerId");
    CREATE INDEX IF NOT EXISTS "IX_Leads_SourceId" ON "leads"."Leads" ("SourceId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_LeadProductInterests_LeadId_ProductId" ON "leads"."LeadProductInterests" ("LeadId", "ProductId");
    CREATE INDEX IF NOT EXISTS "IX_LeadProductInterests_ProductId" ON "leads"."LeadProductInterests" ("ProductId");
    CREATE INDEX IF NOT EXISTS "IX_LeadTimelineEntries_LeadId" ON "leads"."LeadTimelineEntries" ("LeadId");

    INSERT INTO "leads"."LeadSources" ("Id", "Code", "Name", "RequiresPartner", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('10000000-0000-0000-0000-000000000001', 'DIRECT', 'Direct', false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('10000000-0000-0000-0000-000000000002', 'PARTNER', 'Partner', true, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('10000000-0000-0000-0000-000000000003', 'CAMPAIGN', 'Campaign', false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "leads"."LeadCategories" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('20000000-0000-0000-0000-000000000001', 'HOT', 'Hot', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('20000000-0000-0000-0000-000000000002', 'WARM', 'Warm', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('20000000-0000-0000-0000-000000000003', 'COLD', 'Cold', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "leads"."Products" ("Id", "Code", "Name", "CategoryName", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('30000000-0000-0000-0000-000000000001', 'CRM-CORE', 'CRM Core', 'Software', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('30000000-0000-0000-0000-000000000002', 'CRM-SALES', 'Sales Automation', 'Software', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('30000000-0000-0000-0000-000000000003', 'CRM-SUPPORT', 'Customer Support', 'Software', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "leads"."Partners" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('40000000-0000-0000-0000-000000000001', 'PARTNER-A', 'Partner A', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('40000000-0000-0000-0000-000000000002', 'PARTNER-B', 'Partner B', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "leads"."Countries" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('50000000-0000-0000-0000-000000000001', 'NP', 'Nepal', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('50000000-0000-0000-0000-000000000002', 'US', 'United States', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('50000000-0000-0000-0000-000000000003', 'IN', 'India', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "leads"."Industries" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('60000000-0000-0000-0000-000000000001', 'IT', 'Information Technology', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('60000000-0000-0000-0000-000000000002', 'FIN', 'Financial Services', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('60000000-0000-0000-0000-000000000003', 'MFG', 'Manufacturing', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260503193000_LeadsInitial', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260505100000_LeadConversion
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505100000_LeadConversion') THEN
        RETURN;
    END IF;

    ALTER TABLE "leads"."Leads" ADD COLUMN IF NOT EXISTS "ConvertedOpportunityId" uuid NULL;

    CREATE TABLE IF NOT EXISTS "leads"."Clients" (
        "Id" uuid NOT NULL,
        "Name" character varying(250) NOT NULL,
        "CountryId" uuid NOT NULL,
        "IndustryId" uuid NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."ClientContacts" (
        "Id" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Email" character varying(250) NULL,
        "Phone" character varying(50) NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_ClientContacts" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."Opportunities" (
        "Id" uuid NOT NULL,
        "OpportunityNumber" character varying(30) NOT NULL,
        "LeadId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "Title" character varying(250) NOT NULL,
        "EstimatedValue" numeric(18,2) NOT NULL,
        "CurrencyId" uuid NOT NULL,
        "ExpectedCloseDate" timestamp with time zone NULL,
        "OwnerUserId" uuid NOT NULL,
        "Stage" character varying(50) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Opportunities" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Clients_Countries_CountryId') THEN
        ALTER TABLE "leads"."Clients" ADD CONSTRAINT "FK_Clients_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "leads"."Countries" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Clients_Industries_IndustryId') THEN
        ALTER TABLE "leads"."Clients" ADD CONSTRAINT "FK_Clients_Industries_IndustryId" FOREIGN KEY ("IndustryId") REFERENCES "leads"."Industries" ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ClientContacts_Clients_ClientId') THEN
        ALTER TABLE "leads"."ClientContacts" ADD CONSTRAINT "FK_ClientContacts_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "leads"."Clients" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_ClientContacts_ContactId') THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_ClientContacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "leads"."ClientContacts" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Clients_ClientId') THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "leads"."Clients" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Leads_LeadId') THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "leads"."Leads" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Products_ProductId')
       AND to_regclass('"leads"."Products"') IS NOT NULL THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "leads"."Products" ("Id") ON DELETE CASCADE;
    ELSIF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Products_ProductId')
       AND to_regclass('"products"."Products"') IS NOT NULL THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "products"."Products" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Opportunities_ConvertedOpportunityId') THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_Opportunities_ConvertedOpportunityId" FOREIGN KEY ("ConvertedOpportunityId") REFERENCES "leads"."Opportunities" ("Id");
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_Leads_ConvertedOpportunityId" ON "leads"."Leads" ("ConvertedOpportunityId");
    CREATE INDEX IF NOT EXISTS "IX_Clients_CountryId" ON "leads"."Clients" ("CountryId");
    CREATE INDEX IF NOT EXISTS "IX_Clients_IndustryId" ON "leads"."Clients" ("IndustryId");
    CREATE INDEX IF NOT EXISTS "IX_Clients_Name" ON "leads"."Clients" ("Name");
    CREATE INDEX IF NOT EXISTS "IX_ClientContacts_ClientId_Email" ON "leads"."ClientContacts" ("ClientId", "Email");
    CREATE INDEX IF NOT EXISTS "IX_Opportunities_ClientId" ON "leads"."Opportunities" ("ClientId");
    CREATE INDEX IF NOT EXISTS "IX_Opportunities_ContactId" ON "leads"."Opportunities" ("ContactId");
    CREATE INDEX IF NOT EXISTS "IX_Opportunities_LeadId" ON "leads"."Opportunities" ("LeadId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Opportunities_OpportunityNumber" ON "leads"."Opportunities" ("OpportunityNumber");
    CREATE INDEX IF NOT EXISTS "IX_Opportunities_ProductId" ON "leads"."Opportunities" ("ProductId");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505100000_LeadConversion', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260520100000_LeadInteractions
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520100000_LeadInteractions') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "leads"."LeadInteractions" (
        "Id" uuid NOT NULL,
        "LeadId" uuid NOT NULL,
        "InteractionType" character varying(30) NOT NULL,
        "Subject" character varying(250) NULL,
        "Notes" character varying(2000) NOT NULL,
        "InteractionDate" timestamp with time zone NOT NULL,
        "NextFollowUpDate" timestamp with time zone NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_LeadInteractions" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_LeadInteractions_Leads_LeadId') THEN
        ALTER TABLE "leads"."LeadInteractions" ADD CONSTRAINT "FK_LeadInteractions_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "leads"."Leads" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_LeadInteractions_LeadId_InteractionDate" ON "leads"."LeadInteractions" ("LeadId", "InteractionDate");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520100000_LeadInteractions', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260524101000_DecoupleLeadPartnerReference
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524101000_DecoupleLeadPartnerReference') THEN
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Partners_PartnerId') THEN
        ALTER TABLE "leads"."Leads" DROP CONSTRAINT "FK_Leads_Partners_PartnerId";
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524101000_DecoupleLeadPartnerReference', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260524102000_LeadSourceDateRange
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524102000_LeadSourceDateRange') THEN
        RETURN;
    END IF;

    ALTER TABLE "leads"."Leads"
        ADD COLUMN IF NOT EXISTS "SourceStartDate" timestamp with time zone NULL,
        ADD COLUMN IF NOT EXISTS "SourceEndDate" timestamp with time zone NULL;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524102000_LeadSourceDateRange', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260524114000_ProductMaster
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524114000_ProductMaster') THEN
        RETURN;
    END IF;

    CREATE SCHEMA IF NOT EXISTS "products";

    IF to_regclass('"products"."Products"') IS NULL THEN
        IF to_regclass('"leads"."Products"') IS NOT NULL THEN
            ALTER TABLE "leads"."Products" SET SCHEMA "products";
        ELSE
            CREATE TABLE "products"."Products" (
                "Id" uuid NOT NULL,
                "Code" character varying(50) NOT NULL,
                "Name" character varying(200) NOT NULL,
                "Description" text NULL,
                "ProductType" integer NOT NULL DEFAULT 1,
                "DeploymentType" integer NOT NULL DEFAULT 4,
                "IsSubscriptionBased" boolean NOT NULL DEFAULT false,
                "IsLicenseBased" boolean NOT NULL DEFAULT false,
                "IsDeleted" boolean NOT NULL DEFAULT false,
                "CreatedBy" uuid NOT NULL,
                "CreatedOn" timestamp with time zone NOT NULL,
                "UpdatedBy" uuid NULL,
                "UpdatedOn" timestamp with time zone NULL,
                "IsActive" boolean NOT NULL DEFAULT true,
                CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
            );
        END IF;
    END IF;

    ALTER TABLE "products"."Products"
        ADD COLUMN IF NOT EXISTS "ProductType" integer NOT NULL DEFAULT 1,
        ADD COLUMN IF NOT EXISTS "DeploymentType" integer NOT NULL DEFAULT 4,
        ADD COLUMN IF NOT EXISTS "Description" text NULL,
        ADD COLUMN IF NOT EXISTS "IsSubscriptionBased" boolean NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS "IsLicenseBased" boolean NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS "CategoryName" text NULL;

    ALTER TABLE "products"."Products"
        ALTER COLUMN "Name" TYPE character varying(200),
        ALTER COLUMN "Description" TYPE text,
        ALTER COLUMN "ProductType" TYPE integer USING CASE
            WHEN "ProductType"::text ~ '^[0-9]+$' THEN "ProductType"::text::integer
            WHEN upper("ProductType"::text) = 'SOFTWARE' THEN 1
            WHEN upper("ProductType"::text) = 'SERVICE' THEN 2
            WHEN upper("ProductType"::text) = 'ADDON' THEN 3
            WHEN upper("ProductType"::text) = 'HARDWARE' THEN 4
            WHEN "CategoryName" IS NOT NULL AND upper("CategoryName") = 'SERVICE' THEN 2
            WHEN "CategoryName" IS NOT NULL AND upper("CategoryName") = 'ADDON' THEN 3
            WHEN "CategoryName" IS NOT NULL AND upper("CategoryName") = 'HARDWARE' THEN 4
            ELSE 1
        END,
        ALTER COLUMN "DeploymentType" TYPE integer USING CASE
            WHEN "DeploymentType"::text ~ '^[0-9]+$' THEN "DeploymentType"::text::integer
            WHEN upper("DeploymentType"::text) = 'CLOUD' THEN 1
            WHEN upper("DeploymentType"::text) IN ('ONPREMISE', 'ON_PREMISE', 'ON PREMISE') THEN 2
            WHEN upper("DeploymentType"::text) = 'HYBRID' THEN 3
            ELSE 4
        END;

    UPDATE "products"."Products" SET "ProductType" = 1 WHERE "ProductType" NOT IN (1, 2, 3, 4);
    UPDATE "products"."Products" SET "DeploymentType" = 4 WHERE "DeploymentType" NOT IN (1, 2, 3, 4);

    ALTER TABLE "products"."Products" DROP COLUMN IF EXISTS "CategoryName";

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Code" ON "products"."Products" ("Code");
    CREATE INDEX IF NOT EXISTS "IX_Products_Name_ProductType_DeploymentType" ON "products"."Products" ("Name", "ProductType", "DeploymentType");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524114000_ProductMaster', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260527120000_ProductOwnership
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527120000_ProductOwnership') THEN
        RETURN;
    END IF;

    ALTER TABLE "products"."Products"
        ADD COLUMN IF NOT EXISTS "OwnershipType" integer NOT NULL DEFAULT 1,
        ADD COLUMN IF NOT EXISTS "OwnerPartnerId" uuid NULL;

    UPDATE "products"."Products"
    SET "OwnershipType" = 1,
        "OwnerPartnerId" = NULL
    WHERE "OwnershipType" NOT IN (1, 2);

    UPDATE "products"."Products"
    SET "OwnerPartnerId" = NULL
    WHERE "OwnershipType" = 1;

    CREATE INDEX IF NOT EXISTS "IX_Products_OwnerPartnerId" ON "products"."Products" ("OwnerPartnerId");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527120000_ProductOwnership', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260524100000_PartnerManagement
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260524100000_PartnerManagement') THEN
        RETURN;
    END IF;

    CREATE SCHEMA IF NOT EXISTS "partners";

    CREATE TABLE IF NOT EXISTS "partners"."PartnerTypes" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_PartnerTypes" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "partners"."Partners" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "PartnerTypeId" uuid NOT NULL,
        "CountryId" uuid NOT NULL,
        "ContactPerson" character varying(150) NULL,
        "PhoneNumber" character varying(50) NULL,
        "Email" character varying(250) NULL,
        "Address" character varying(500) NULL,
        "Remarks" character varying(1000) NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Partners" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Partners_PartnerTypes_PartnerTypeId') THEN
        ALTER TABLE "partners"."Partners" ADD CONSTRAINT "FK_Partners_PartnerTypes_PartnerTypeId"
        FOREIGN KEY ("PartnerTypeId") REFERENCES "partners"."PartnerTypes" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_PartnerTypes_Code" ON "partners"."PartnerTypes" ("Code");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Partners_Code" ON "partners"."Partners" ("Code");
    CREATE INDEX IF NOT EXISTS "IX_Partners_Name_PartnerTypeId_CountryId" ON "partners"."Partners" ("Name", "PartnerTypeId", "CountryId");
    CREATE INDEX IF NOT EXISTS "IX_Partners_PartnerTypeId" ON "partners"."Partners" ("PartnerTypeId");

    INSERT INTO "partners"."PartnerTypes" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('41000000-0000-0000-0000-000000000001', 'CONSULTANT', 'Consultant', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000002', 'RESELLER', 'Reseller', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000003', 'AFFILIATE', 'Affiliate', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000004', 'VENDOR', 'Vendor', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000005', 'SALES-AGENT', 'Sales Agent', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000006', 'OTHER', 'Other', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    IF to_regclass('"leads"."Partners"') IS NOT NULL THEN
        INSERT INTO "partners"."Partners"
            ("Id", "Code", "Name", "PartnerTypeId", "CountryId", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn", "IsActive")
        SELECT
            "Id",
            "Code",
            "Name",
            '41000000-0000-0000-0000-000000000006',
            '50000000-0000-0000-0000-000000000001',
            "CreatedBy",
            "CreatedOn",
            "UpdatedBy",
            "UpdatedOn",
            "IsActive"
        FROM "leads"."Partners"
        ON CONFLICT ("Id") DO NOTHING;
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260524100000_PartnerManagement', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260526110000_PartnerProductAssignments
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526110000_PartnerProductAssignments') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "partners"."PartnerProducts" (
        "Id" uuid NOT NULL,
        "PartnerId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_PartnerProducts" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_PartnerProducts_Partners_PartnerId') THEN
        ALTER TABLE "partners"."PartnerProducts" ADD CONSTRAINT "FK_PartnerProducts_Partners_PartnerId"
        FOREIGN KEY ("PartnerId") REFERENCES "partners"."Partners" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_PartnerProducts_PartnerId_ProductId" ON "partners"."PartnerProducts" ("PartnerId", "ProductId");

    INSERT INTO "partners"."PartnerTypes" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES ('41000000-0000-0000-0000-000000000007', 'SUPPLIER', 'Supplier', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO NOTHING;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260526110000_PartnerProductAssignments', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260527100000_PartnerTypeEcosystem
-- -------------------------------------------------------------------------
DO $migration$
DECLARE
    old_sales_agent_id uuid;
    new_sales_agent_id uuid;
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527100000_PartnerTypeEcosystem') THEN
        RETURN;
    END IF;

    SELECT "Id" INTO old_sales_agent_id
    FROM "partners"."PartnerTypes"
    WHERE "Code" = 'SALES-AGENT'
    LIMIT 1;

    SELECT "Id" INTO new_sales_agent_id
    FROM "partners"."PartnerTypes"
    WHERE "Code" = 'SALES_AGENT'
    LIMIT 1;

    IF old_sales_agent_id IS NOT NULL AND new_sales_agent_id IS NULL THEN
        UPDATE "partners"."PartnerTypes"
        SET "Code" = 'SALES_AGENT',
            "Name" = 'Sales Agent',
            "IsActive" = true
        WHERE "Id" = old_sales_agent_id;
    ELSIF old_sales_agent_id IS NOT NULL AND new_sales_agent_id IS NOT NULL THEN
        UPDATE "partners"."Partners"
        SET "PartnerTypeId" = new_sales_agent_id
        WHERE "PartnerTypeId" = old_sales_agent_id;

        DELETE FROM "partners"."PartnerTypes"
        WHERE "Id" = old_sales_agent_id;
    END IF;

    INSERT INTO "partners"."PartnerTypes" ("Id", "Code", "Name", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('41000000-0000-0000-0000-000000000002', 'RESELLER', 'Reseller', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000008', 'DISTRIBUTOR', 'Distributor', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000004', 'VENDOR', 'Vendor', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000007', 'SUPPLIER', 'Supplier', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000005', 'SALES_AGENT', 'Sales Agent', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000003', 'AFFILIATE', 'Affiliate', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000001', 'CONSULTANT', 'Consultant', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000009', 'TECHNOLOGY_PARTNER', 'Technology Partner', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000010', 'IMPLEMENTATION_PARTNER', 'Implementation Partner', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000011', 'SERVICE_PARTNER', 'Service Partner', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000012', 'STRATEGIC_PARTNER', 'Strategic Partner', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('41000000-0000-0000-0000-000000000006', 'OTHER', 'Other', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Code") DO UPDATE
    SET "Name" = EXCLUDED."Name",
        "IsActive" = true;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527100000_PartnerTypeEcosystem', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260527113000_RemoveDistributorPartnerType
-- -------------------------------------------------------------------------
DO $migration$
DECLARE
    distributor_id uuid;
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260527113000_RemoveDistributorPartnerType') THEN
        RETURN;
    END IF;

    SELECT "Id" INTO distributor_id
    FROM "partners"."PartnerTypes"
    WHERE "Code" = 'DISTRIBUTOR'
    LIMIT 1;

    IF distributor_id IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM "partners"."Partners"
            WHERE "PartnerTypeId" = distributor_id
        ) THEN
            UPDATE "partners"."PartnerTypes"
            SET "IsActive" = false
            WHERE "Id" = distributor_id;
        ELSE
            DELETE FROM "partners"."PartnerTypes"
            WHERE "Id" = distributor_id;
        END IF;
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260527113000_RemoveDistributorPartnerType', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260520110000_OpportunityManualCreate
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520110000_OpportunityManualCreate') THEN
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Leads_LeadId') THEN
        ALTER TABLE "leads"."Opportunities" DROP CONSTRAINT "FK_Opportunities_Leads_LeadId";
    END IF;

    ALTER TABLE "leads"."Opportunities" ALTER COLUMN "LeadId" DROP NOT NULL;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Leads_LeadId') THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Leads_LeadId"
        FOREIGN KEY ("LeadId") REFERENCES "leads"."Leads" ("Id");
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520110000_OpportunityManualCreate', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260522120000_OpportunityPipeline
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260522120000_OpportunityPipeline') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "leads"."OpportunityStages" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Sequence" integer NOT NULL,
        "IsDefault" boolean NOT NULL,
        "IsFinal" boolean NOT NULL,
        "IsWonStage" boolean NOT NULL,
        "IsLostStage" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_OpportunityStages" PRIMARY KEY ("Id")
    );

    CREATE UNIQUE INDEX IF NOT EXISTS "IX_OpportunityStages_Name" ON "leads"."OpportunityStages" ("Name");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_OpportunityStages_Sequence" ON "leads"."OpportunityStages" ("Sequence");

    INSERT INTO "leads"."OpportunityStages" ("Id", "Name", "Sequence", "IsDefault", "IsFinal", "IsWonStage", "IsLostStage", "IsDeleted", "CreatedBy", "CreatedOn", "IsActive")
    VALUES
        ('80000000-0000-0000-0000-000000000001', 'New Opportunity', 1, true, false, false, false, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('80000000-0000-0000-0000-000000000002', 'Discovery', 2, false, false, false, false, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('80000000-0000-0000-0000-000000000003', 'Proposal Sent', 3, false, false, false, false, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('80000000-0000-0000-0000-000000000004', 'Negotiation', 4, false, false, false, false, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('80000000-0000-0000-0000-000000000005', 'Won', 5, false, true, true, false, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true),
        ('80000000-0000-0000-0000-000000000006', 'Lost', 6, false, true, false, true, false, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2026-01-01 00:00:00+00', true)
    ON CONFLICT ("Id") DO NOTHING;

    ALTER TABLE "leads"."Opportunities"
        ADD COLUMN IF NOT EXISTS "StageId" uuid NULL,
        ADD COLUMN IF NOT EXISTS "Status" character varying(30) NOT NULL DEFAULT 'Open',
        ADD COLUMN IF NOT EXISTS "FinalAmount" numeric(18,2) NULL,
        ADD COLUMN IF NOT EXISTS "ClosedDate" timestamp with time zone NULL,
        ADD COLUMN IF NOT EXISTS "ClosingNote" character varying(1000) NULL,
        ADD COLUMN IF NOT EXISTS "LostReason" character varying(500) NULL;

    UPDATE "leads"."Opportunities"
    SET "StageId" = CASE
        WHEN LOWER("Stage") = 'discovery' THEN '80000000-0000-0000-0000-000000000002'::uuid
        WHEN LOWER("Stage") = 'proposal sent' THEN '80000000-0000-0000-0000-000000000003'::uuid
        WHEN LOWER("Stage") = 'negotiation' THEN '80000000-0000-0000-0000-000000000004'::uuid
        WHEN LOWER("Stage") = 'won' THEN '80000000-0000-0000-0000-000000000005'::uuid
        WHEN LOWER("Stage") = 'lost' THEN '80000000-0000-0000-0000-000000000006'::uuid
        ELSE '80000000-0000-0000-0000-000000000001'::uuid
    END,
    "Stage" = CASE
        WHEN LOWER("Stage") = 'new' THEN 'New Opportunity'
        ELSE "Stage"
    END
    WHERE "StageId" IS NULL;

    UPDATE "leads"."Opportunities"
    SET "StageId" = '80000000-0000-0000-0000-000000000001'::uuid
    WHERE "StageId" IS NULL;

    ALTER TABLE "leads"."Opportunities" ALTER COLUMN "StageId" SET NOT NULL;

    CREATE INDEX IF NOT EXISTS "IX_Opportunities_StageId" ON "leads"."Opportunities" ("StageId");

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_OpportunityStages_StageId') THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_OpportunityStages_StageId"
        FOREIGN KEY ("StageId") REFERENCES "leads"."OpportunityStages" ("Id") ON DELETE RESTRICT;
    END IF;

    CREATE TABLE IF NOT EXISTS "leads"."OpportunityActivities" (
        "Id" uuid NOT NULL,
        "OpportunityId" uuid NOT NULL,
        "ActivityType" character varying(30) NOT NULL,
        "Subject" character varying(250) NULL,
        "Notes" character varying(2000) NOT NULL,
        "ActivityDate" timestamp with time zone NOT NULL,
        "FollowUpDate" timestamp with time zone NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_OpportunityActivities" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "leads"."OpportunityStageHistories" (
        "Id" uuid NOT NULL,
        "OpportunityId" uuid NOT NULL,
        "FromStageId" uuid NULL,
        "ToStageId" uuid NOT NULL,
        "Remarks" character varying(1000) NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_OpportunityStageHistories" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OpportunityActivities_Opportunities_OpportunityId') THEN
        ALTER TABLE "leads"."OpportunityActivities" ADD CONSTRAINT "FK_OpportunityActivities_Opportunities_OpportunityId"
        FOREIGN KEY ("OpportunityId") REFERENCES "leads"."Opportunities" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OpportunityStageHistories_Opportunities_OpportunityId') THEN
        ALTER TABLE "leads"."OpportunityStageHistories" ADD CONSTRAINT "FK_OpportunityStageHistories_Opportunities_OpportunityId"
        FOREIGN KEY ("OpportunityId") REFERENCES "leads"."Opportunities" ("Id") ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OpportunityStageHistories_OpportunityStages_FromStageId') THEN
        ALTER TABLE "leads"."OpportunityStageHistories" ADD CONSTRAINT "FK_OpportunityStageHistories_OpportunityStages_FromStageId"
        FOREIGN KEY ("FromStageId") REFERENCES "leads"."OpportunityStages" ("Id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OpportunityStageHistories_OpportunityStages_ToStageId') THEN
        ALTER TABLE "leads"."OpportunityStageHistories" ADD CONSTRAINT "FK_OpportunityStageHistories_OpportunityStages_ToStageId"
        FOREIGN KEY ("ToStageId") REFERENCES "leads"."OpportunityStages" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_OpportunityActivities_OpportunityId_ActivityDate" ON "leads"."OpportunityActivities" ("OpportunityId", "ActivityDate");
    CREATE INDEX IF NOT EXISTS "IX_OpportunityStageHistories_FromStageId" ON "leads"."OpportunityStageHistories" ("FromStageId");
    CREATE INDEX IF NOT EXISTS "IX_OpportunityStageHistories_OpportunityId_CreatedOn" ON "leads"."OpportunityStageHistories" ("OpportunityId", "CreatedOn");
    CREATE INDEX IF NOT EXISTS "IX_OpportunityStageHistories_ToStageId" ON "leads"."OpportunityStageHistories" ("ToStageId");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260522120000_OpportunityPipeline', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260721103000_OpportunityProposalDocuments
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260721103000_OpportunityProposalDocuments') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "leads"."OpportunityDocuments" (
        "Id" uuid NOT NULL,
        "OpportunityId" uuid NOT NULL,
        "DocumentType" character varying(50) NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "StoredFileName" character varying(255) NOT NULL,
        "FilePath" character varying(500) NOT NULL,
        "ContentType" character varying(150) NOT NULL,
        "FileSize" bigint NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_OpportunityDocuments" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_OpportunityDocuments_Opportunities_OpportunityId') THEN
        ALTER TABLE "leads"."OpportunityDocuments" ADD CONSTRAINT "FK_OpportunityDocuments_Opportunities_OpportunityId"
        FOREIGN KEY ("OpportunityId") REFERENCES "leads"."Opportunities" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_OpportunityDocuments_OpportunityId_DocumentType_IsActive"
        ON "leads"."OpportunityDocuments" ("OpportunityId", "DocumentType", "IsActive");

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260721103000_OpportunityProposalDocuments', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260528140000_ClientProductMappings
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260528140000_ClientProductMappings') THEN
        RETURN;
    END IF;

    CREATE TABLE IF NOT EXISTS "clients"."ClientProducts" (
        "Id" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "ProductId" uuid NOT NULL,
        "RelationshipStatus" character varying(100) NOT NULL,
        "OpportunityId" uuid NULL,
        "OwnerUserId" uuid NULL,
        "StartDate" timestamp with time zone NULL,
        "EndDate" timestamp with time zone NULL,
        "Notes" character varying(1000) NULL,
        "IsDeleted" boolean NOT NULL DEFAULT false,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_ClientProducts" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ClientProducts_Clients_ClientId') THEN
        ALTER TABLE "clients"."ClientProducts" ADD CONSTRAINT "FK_ClientProducts_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "clients"."Clients" ("Id") ON DELETE CASCADE;
    END IF;

    CREATE INDEX IF NOT EXISTS "IX_ClientProducts_ClientId" ON "clients"."ClientProducts" ("ClientId");
    CREATE INDEX IF NOT EXISTS "IX_ClientProducts_ProductId" ON "clients"."ClientProducts" ("ProductId");
    CREATE INDEX IF NOT EXISTS "IX_ClientProducts_OpportunityId" ON "clients"."ClientProducts" ("OpportunityId");
    CREATE INDEX IF NOT EXISTS "IX_ClientProducts_OwnerUserId" ON "clients"."ClientProducts" ("OwnerUserId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClientProducts_ClientId_ProductId"
        ON "clients"."ClientProducts" ("ClientId", "ProductId")
        WHERE "IsDeleted" = false;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260528140000_ClientProductMappings', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

-- -------------------------------------------------------------------------
-- 20260602110000_LinkLeadsToClientModule
-- -------------------------------------------------------------------------
DO $migration$
BEGIN
    IF EXISTS (SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260602110000_LinkLeadsToClientModule') THEN
        RETURN;
    END IF;

    CREATE SCHEMA IF NOT EXISTS "clients";

    CREATE TABLE IF NOT EXISTS "clients"."ClientTypes" (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_ClientTypes" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "clients"."Clients" (
        "Id" uuid NOT NULL,
        "ClientCode" character varying(50) NOT NULL,
        "Name" character varying(250) NOT NULL,
        "NormalizedName" character varying(250) NOT NULL,
        "ShortName" character varying(100) NULL,
        "ClientTypeId" uuid NULL,
        "IndustryId" uuid NULL,
        "CountryId" uuid NOT NULL,
        "Address" character varying(500) NULL,
        "Website" character varying(250) NULL,
        "TaxNumber" character varying(100) NULL,
        "RegistrationNumber" character varying(100) NULL,
        "AccountOwnerUserId" uuid NULL,
        "Notes" character varying(2000) NULL,
        "Status" integer NOT NULL DEFAULT 1,
        "IsDeleted" boolean NOT NULL DEFAULT false,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
    );

    CREATE TABLE IF NOT EXISTS "clients"."ClientContacts" (
        "Id" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "FullName" character varying(250) NOT NULL,
        "Designation" character varying(150) NULL,
        "Department" character varying(150) NULL,
        "Email" character varying(320) NULL,
        "NormalizedEmail" character varying(320) NULL,
        "Phone" character varying(50) NULL,
        "Mobile" character varying(50) NULL,
        "IsPrimary" boolean NOT NULL DEFAULT false,
        "Status" integer NOT NULL DEFAULT 1,
        "Notes" character varying(1000) NULL,
        "IsDeleted" boolean NOT NULL DEFAULT false,
        "CreatedBy" uuid NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedBy" uuid NULL,
        "UpdatedOn" timestamp with time zone NULL,
        "IsActive" boolean NOT NULL DEFAULT true,
        CONSTRAINT "PK_ClientContacts" PRIMARY KEY ("Id")
    );

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ClientContacts_Clients_ClientId' AND conrelid = '"clients"."ClientContacts"'::regclass) THEN
        ALTER TABLE "clients"."ClientContacts" ADD CONSTRAINT "FK_ClientContacts_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "clients"."Clients" ("Id") ON DELETE CASCADE;
    END IF;

    ALTER TABLE "leads"."Leads"
        ADD COLUMN IF NOT EXISTS "ClientId" uuid NULL,
        ADD COLUMN IF NOT EXISTS "ClientContactId" uuid NULL;

    CREATE INDEX IF NOT EXISTS "IX_Leads_ClientId" ON "leads"."Leads" ("ClientId");
    CREATE INDEX IF NOT EXISTS "IX_Leads_ClientContactId" ON "leads"."Leads" ("ClientContactId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clients_ClientCode" ON "clients"."Clients" ("ClientCode");
    CREATE INDEX IF NOT EXISTS "IX_Clients_NormalizedName_CountryId" ON "clients"."Clients" ("NormalizedName", "CountryId");
    CREATE INDEX IF NOT EXISTS "IX_ClientContacts_ClientId" ON "clients"."ClientContacts" ("ClientId");
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClientContacts_ClientId_NormalizedEmail"
        ON "clients"."ClientContacts" ("ClientId", "NormalizedEmail")
        WHERE "NormalizedEmail" IS NOT NULL AND "IsDeleted" = false;

    INSERT INTO "clients"."Clients"
        ("Id", "ClientCode", "Name", "NormalizedName", "IndustryId", "CountryId", "Address", "Website", "Status", "IsDeleted", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn", "IsActive")
    WITH lead_clients AS (
        SELECT
            UPPER(TRIM("CompanyName")) AS normalized_name,
            MIN(TRIM("CompanyName")) AS name,
            "CountryId",
            (array_agg("IndustryId" ORDER BY "CreatedOn"))[1] AS industry_id,
            MIN("Address") AS address,
            MIN("Website") AS website,
            (array_agg("CreatedBy" ORDER BY "CreatedOn"))[1] AS created_by,
            MIN("CreatedOn") AS created_on
        FROM "leads"."Leads"
        WHERE "ClientId" IS NULL
            AND COALESCE(TRIM("CompanyName"), '') <> ''
            AND "CountryId" <> '00000000-0000-0000-0000-000000000000'::uuid
        GROUP BY UPPER(TRIM("CompanyName")), "CountryId"
    ),
    numbered AS (
        SELECT
            *,
            ROW_NUMBER() OVER (ORDER BY normalized_name, "CountryId") AS rn
        FROM lead_clients lc
        WHERE NOT EXISTS (
            SELECT 1 FROM "clients"."Clients" c
            WHERE c."NormalizedName" = lc.normalized_name
                AND c."CountryId" = lc."CountryId"
                AND c."IsDeleted" = false
        )
    )
    SELECT
        (md5('lead-client:' || normalized_name || ':' || "CountryId"))::uuid,
        'CL-' || UPPER(SUBSTRING(md5(normalized_name || ':' || "CountryId") FROM 1 FOR 10)),
        name,
        normalized_name,
        industry_id,
        "CountryId",
        address,
        website,
        1,
        false,
        COALESCE(created_by, '00000000-0000-0000-0000-000000000000'::uuid),
        COALESCE(created_on, NOW()),
        NULL,
        NULL,
        true
    FROM numbered
    ON CONFLICT ("Id") DO NOTHING;

    UPDATE "leads"."Leads" l
    SET "ClientId" = c."Id"
    FROM "clients"."Clients" c
    WHERE l."ClientId" IS NULL
        AND c."NormalizedName" = UPPER(TRIM(l."CompanyName"))
        AND c."CountryId" = l."CountryId"
        AND c."IsDeleted" = false;

    INSERT INTO "clients"."ClientContacts"
        ("Id", "ClientId", "FirstName", "LastName", "FullName", "Designation", "Email", "NormalizedEmail", "Phone", "Mobile", "IsPrimary", "Status", "IsDeleted", "CreatedBy", "CreatedOn", "UpdatedBy", "UpdatedOn", "IsActive")
    WITH lead_contacts AS (
        SELECT DISTINCT ON (l."ClientId", UPPER(TRIM(COALESCE(l."Email", ''))), UPPER(TRIM(l."ContactPersonName")))
            l."ClientId",
            TRIM(l."ContactPersonName") AS full_name,
            NULLIF(TRIM(l."JobTitle"), '') AS designation,
            NULLIF(TRIM(l."Email"), '') AS email,
            UPPER(NULLIF(TRIM(l."Email"), '')) AS normalized_email,
            NULLIF(TRIM(l."Phone"), '') AS phone,
            NULLIF(TRIM(l."AlternatePhone"), '') AS mobile,
            l."CreatedBy" AS created_by,
            l."CreatedOn" AS created_on
        FROM "leads"."Leads" l
        WHERE l."ClientContactId" IS NULL
            AND l."ClientId" IS NOT NULL
            AND COALESCE(TRIM(l."ContactPersonName"), '') <> ''
        ORDER BY l."ClientId", UPPER(TRIM(COALESCE(l."Email", ''))), UPPER(TRIM(l."ContactPersonName")), l."CreatedOn"
    )
    SELECT
        (md5('lead-contact:' || "ClientId" || ':' || COALESCE(normalized_email, UPPER(full_name))))::uuid,
        "ClientId",
        COALESCE(NULLIF(split_part(full_name, ' ', 1), ''), full_name),
        COALESCE(NULLIF(substring(full_name from '\s(.+)$'), ''), '-'),
        full_name,
        designation,
        email,
        normalized_email,
        phone,
        mobile,
        NOT EXISTS (SELECT 1 FROM "clients"."ClientContacts" existing WHERE existing."ClientId" = lead_contacts."ClientId" AND existing."IsPrimary" = true AND existing."IsDeleted" = false),
        1,
        false,
        COALESCE(created_by, '00000000-0000-0000-0000-000000000000'::uuid),
        COALESCE(created_on, NOW()),
        NULL,
        NULL,
        true
    FROM lead_contacts
    WHERE NOT EXISTS (
        SELECT 1 FROM "clients"."ClientContacts" cc
        WHERE cc."ClientId" = lead_contacts."ClientId"
            AND cc."IsDeleted" = false
            AND (
                (lead_contacts.normalized_email IS NOT NULL AND cc."NormalizedEmail" = lead_contacts.normalized_email)
                OR (lead_contacts.normalized_email IS NULL AND UPPER(cc."FullName") = UPPER(lead_contacts.full_name))
            )
    )
    ON CONFLICT ("Id") DO NOTHING;

    UPDATE "leads"."Leads" l
    SET "ClientContactId" = cc."Id"
    FROM "clients"."ClientContacts" cc
    WHERE l."ClientContactId" IS NULL
        AND l."ClientId" = cc."ClientId"
        AND cc."IsDeleted" = false
        AND (
            (NULLIF(TRIM(l."Email"), '') IS NOT NULL AND cc."NormalizedEmail" = UPPER(TRIM(l."Email")))
            OR (NULLIF(TRIM(l."Email"), '') IS NULL AND UPPER(cc."FullName") = UPPER(TRIM(l."ContactPersonName")))
        );

    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Clients_ClientId') THEN
        ALTER TABLE "leads"."Opportunities" DROP CONSTRAINT "FK_Opportunities_Clients_ClientId";
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_ClientContacts_ContactId') THEN
        ALTER TABLE "leads"."Opportunities" DROP CONSTRAINT "FK_Opportunities_ClientContacts_ContactId";
    END IF;

    UPDATE "leads"."Opportunities" o
    SET "ClientId" = l."ClientId",
        "ContactId" = l."ClientContactId"
    FROM "leads"."Leads" l
    WHERE o."LeadId" = l."Id"
        AND l."ClientId" IS NOT NULL
        AND l."ClientContactId" IS NOT NULL;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_Clients_ClientId')
        AND NOT EXISTS (
            SELECT 1 FROM "leads"."Leads" l
            LEFT JOIN "clients"."Clients" c ON c."Id" = l."ClientId"
            WHERE l."ClientId" IS NOT NULL AND c."Id" IS NULL
        ) THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "clients"."Clients" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Leads_ClientContacts_ClientContactId')
        AND NOT EXISTS (
            SELECT 1 FROM "leads"."Leads" l
            LEFT JOIN "clients"."ClientContacts" cc ON cc."Id" = l."ClientContactId"
            WHERE l."ClientContactId" IS NOT NULL AND cc."Id" IS NULL
        ) THEN
        ALTER TABLE "leads"."Leads" ADD CONSTRAINT "FK_Leads_ClientContacts_ClientContactId"
        FOREIGN KEY ("ClientContactId") REFERENCES "clients"."ClientContacts" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_Clients_ClientId')
        AND NOT EXISTS (
            SELECT 1 FROM "leads"."Opportunities" o
            LEFT JOIN "clients"."Clients" c ON c."Id" = o."ClientId"
            WHERE c."Id" IS NULL
        ) THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "clients"."Clients" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Opportunities_ClientContacts_ContactId')
        AND NOT EXISTS (
            SELECT 1 FROM "leads"."Opportunities" o
            LEFT JOIN "clients"."ClientContacts" cc ON cc."Id" = o."ContactId"
            WHERE cc."Id" IS NULL
        ) THEN
        ALTER TABLE "leads"."Opportunities" ADD CONSTRAINT "FK_Opportunities_ClientContacts_ContactId"
        FOREIGN KEY ("ContactId") REFERENCES "clients"."ClientContacts" ("Id") ON DELETE RESTRICT;
    END IF;

    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260602110000_LinkLeadsToClientModule', '8.0.24')
    ON CONFLICT ("MigrationId") DO NOTHING;
END
$migration$;

COMMIT;
