<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ERP.Identity\ERP.Identity.csproj" />
    <ProjectReference Include="..\..\Leads\Leads.Infrastructure\Leads.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Opportunities\Opportunities.Infrastructure\Opportunities.Infrastructure.csproj" />
    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
    <ProjectReference Include="..\Notifications.Domain\Notifications.Domain.csproj" />
  </ItemGroup>

</Project>
